apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-backend
  template:
    metadata:
      labels:
        app: shopping-backend
    spec:
      containers:
      - name: shopping-backend
        image: madhu58/shopping-backend:v1
        ports:
        - containerPort: 5002